# Generated by Django 5.1.2 on 2025-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
