# Generated by Django 5.1.2 on 2025-06-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjid', '0002_donation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
