# Generated by Django 5.1.2 on 2025-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjid', '0003_disbursement_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
