# Generated by Django 5.1.2 on 2025-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjid', '0004_donation_bank_account_donation_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationentry',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
